version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - redis-net
    command: redis-server --save "" --appendonly no

networks:
  redis-net:
    driver: bridge